<?php
/**
 * Created by PhpStorm.
 * User: jomon
 * Date: 16/1/19
 * Time: 5:40 PM
 */

namespace codexten\yii\settings;

use codexten\yii\base\Module;
use codexten\yii\settings\components\Section;
use Yii;
use yii\di\Instance;

class SettingsModule extends Module
{
    /**
     * @var Section[]
     */
    public $sections = [];

    public function init()
    {
        foreach ($this->sections as $key => $section) {
            if (!isset($section['class'])) {
                $section['class'] = Section::class;
            }
            $this->sections[$key] = Instance::ensure($section);

        }

        parent::init(); // TODO: Change the autogenerated stub
    }

    public static function getMenuItems()
    {
        $items = [];
        foreach (self::module()->sections as $key => $section) {
            $items[] = [
                'label' => $section->label,
                'icon' => $section->icon,
                'url' => ['/settings/index', 'key' => $key],
            ];
        }

        return $items;
    }

    /**
     * @return static
     */
    public static function module()
    {
        return Yii::$app->getModule('settings');
    }
}